#!/usr/bin/with-contenv bash

cat <<EOF
---
VueTorrent Theme Installer
Source: https://github.com/WDaan/VueTorrent
---
EOF

RESPONSE=$(curl -s -L https://api.github.com/repos/wdaan/vuetorrent/releases/latest)

TAG=$(echo "$RESPONSE" \
  | grep tag_name \
  | cut -d : -f 2,3 \
  | tr -d \", \
  | xargs)

LATEST_RELEASE=$(echo "$RESPONSE" \
  | grep "browser_download_url.*zip" \
  | cut -d : -f 2,3 \
  | tr -d \" \
  | xargs) # to trim whitespace

CURRENT=/current_version.txt

DIR=/vuetorrent

ZIP=vuetorrent.zip

if [ -e $CURRENT ]; then
  echo "$CURRENT exists"

  if [ `cat $CURRENT` == $TAG ] && [ -d $DIR ]; then
    echo "Latest version installed: $TAG. Exiting."
    exit
  fi
fi

echo "Running installer..."

HTTP_CODE=$(curl --silent -O -J -L $LATEST_RELEASE --write-out "%{http_code}" "$@")

if [ $HTTP_CODE == 404 ]; then
  echo "Error downloading zip: $LATEST_RELEASE. Exiting."
  exit
fi

if [ -d $DIR ] && [ -f $ZIP ]; then
  echo "Removing $DIR"
  rm -rf $DIR
fi

unzip $ZIP -d /

rm $ZIP

echo $TAG > $CURRENT

echo "Done! The theme is installed in the root folder. Apply it from WEBUI settings."
